yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit')
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView


from django.urls import path, reverse_lazy


from . import views


app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
            success_url=reverse_lazy(
                'users:password_change_done'
            )
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy(
                'users:password_reset_complete'
            ),
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('group/<slug:slug>/', include('posts.urls', namespace='groups')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='название группы')
    description = models.TextField(verbose_name='описание')
    slug = models.SlugField(
        max_length=50,
        unique=True,
        verbose_name='Url адрес'
    )

    class Meta:
        verbose_name = 'группа'
        verbose_name_plural = 'группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='текст')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='group_posts',
        blank=True,
        null=True,
        verbose_name='группа'
    )

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'
        ordering = ['-pub_date']

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group']
        help_texts = {
            'group': 'Группа, к которой будет относиться пост',
            'text': 'Текст нового поста'
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.core.paginator import Paginator

from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.decorators import login_required

from .forms import PostForm
from .models import Post, Group, User


def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(
        request,
        'posts/index.html',
        {'page_obj': page_obj}
    )


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.group_posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(
        request,
        'posts/group_list.html',
        {'group': group, 'page_obj': page_obj}
    )


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = Post.objects.all().filter(author__username=username)
    count = posts.count()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(
        request,
        'posts/profile.html',
        {
            'page_obj': page_obj,
            'author': author,
            'count': count
        }
    )


def post_detail(request, post_id):
    post_text = Post.objects.get(id=post_id)
    counter = Post.objects.filter(author=post_text.author).count()
    return render(
        request,
        'posts/post_detail.html',
        {
            'post_text': post_text,
            'counter': counter,
        }
    )


@login_required
def post_create(request):
    is_edit = False
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    return render(
        request,
        'posts/create_post.html',
        {
            'form': form,
            'is_edit': is_edit
        }
    )


@login_required
def post_edit(request, post_id):
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    if post.author == request.user:
        form = PostForm(request.POST or None, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect('posts:post_detail', post.pk)
        context = {'form': form, "is_edit": is_edit}
        return render(request, "posts/create_post.html", context)

yatube/users/views.py
from django.views.generic import CreateView


from django.urls import reverse_lazy


from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block page-title %}Об авторе проекта{% endblock page-title %}
{% block content %}
<main>
  <div class="container py-5">
    <h1>Привет, я автор</h1>
      <p>
        Тут я размещу информацию о себе, используя свои умения верстать.
        Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
      </p>
  </div>
</main>
{% endblock %} 

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block page-title %}Технологии{% endblock page-title %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="row">
      <h1>Вот что я умею</h1>
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Python
          </li>
          <li class="list-group-item">
            Django
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        <p>Текст страницы "Технологии"</p>
      </article>
    </div>
  </div>
</main>
{% endblock %} 

yatube/templates/base.html
<!DOCTYPE html> 
<html lang="ru">
  {% load static %}          
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <link rel="icon" href="{% static "img/fav/fav.ico" type="image" %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "img/fav/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href= "{% static "img/fav/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "img/fav/favicon-16x16.png" %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#fffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
    {% block page-title %}
      Yatube
    {% endblock page-title %}
    </title>   
  </head>
  <body>      
    <header>
      {% include 'includes/header.html' %}
    </header>
    {% block content %}
      Контент не подвезли
    {% endblock content %}
    {% include 'includes/footer.html' %} 
  </body>
</html> 

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer> 

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
       {% with request.resolver_match.view_name as view_name %}  
          <li class="nav-item">              
             <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
                href="{% url 'about:author' %}"
             >
                Об авторе
             </a>
          </li>
       {% endwith %} 
       {% with request.resolver_match.view_name as view_name %}  
       <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
             href="{% url 'about:tech' %}"
          >
             Технологии
          </a>
       </li>
    {% endwith %} 
      {% if request.user.is_authenticated %}
      {% with request.resolver_match.view_name as view_name %}
      <li class="nav-item"> 
        <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}"
           href="{% url 'posts:post_create' %}"
        >
           Новая запись
        </a>
      </li>
      {% endwith %}
      {% with request.resolver_match.view_name as view_name %}  
      <li class="nav-item">              
         <a class="nav-link {% if view_name  == 'users:password_change' %}active{% endif %}" 
            href="{% url 'users:password_change' %}"
         >
            Изменить пароль
         </a>
      </li>
   {% endwith %} 
   {% with request.resolver_match.view_name as view_name %}  
   <li class="nav-item">              
      <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}" 
         href="{% url 'users:logout' %}"
      >
         Выйти
      </a>
   </li>
{% endwith %} 
      <li>
        Пользователь: {{ user.username }}
      </li>
      {% else %}
      {% with request.resolver_match.view_name as view_name %}  
      <li class="nav-item">              
         <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" 
            href="{% url 'users:login' %}"
         >
            Войти
         </a>
      </li>
   {% endwith %} 
   {% with request.resolver_match.view_name as view_name %}  
   <li class="nav-item">              
      <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" 
         href="{% url 'users:signup' %}"
      >
        Регистрация
      </a>
   </li>
{% endwith %} 
      {% endif %}
    </ul>
  </div>
</nav>      

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block page-title %}
   Новый пост
{% endblock page-title %}
{% block content %}
  <body>	   
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                Добавить запись
                {% endif %}
              </div>
              <div class="card-body">        
                <form method="post" action=" ">
                  {% csrf_token %}            
                  {% for field in form %}
                  {% load user_filters %}
                      <div class="form-group row my-3 p-3">
                        <label for="{{ field.id_for_label }}">
                          {{ field.label }}
                            {% if field.field.required %}                  
                              <span class="required text-danger" >*</span>
                            {% endif %}                  
                        </label>
                        {{ field|addclass:'form-control' }} 
                          {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                              {{ field.help_text|safe }}
                            </small>
                          {% endif %}
                      </div>
                  {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
  {% endblock %}
  {% comment %}
  {% block content %}
  <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}
            </div>
            <div class="card-body">
              {% if form.errors %}
                  {% for field in form %}
                  {% for error in field.errors %}
                      <div class="alert alert-danger">
                      {{ error|escape }}
                      </div>
                  {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                      {{ error|escape }}
                  </div>
                  {% endfor %}
              {% endif %}
              <form method="post" action="{{ request.get_full_path }}">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
                {% endfor %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
  </div>
  {% endblock %}
  {% endcomment %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block page-title %}
  Записи сообщества {{ group.title }}
{% endblock page-title %}
{% block content %}
<main>
  <div class="container py-5">
    <h1>
      Записи сообщества {{ group.title }}
    </h1>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
          {% if not forloop.last %}
            <hr>
          {% endif %}
      </article>
    {% endfor %}
    <hr>
    {% include 'posts/includes/paginator.html' %}
  </div>
</main>
{% endblock %}
 

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}
 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block page-title %}Последние обновления на сайте{% endblock page-title %}
{% block content %}
<main>
  <div class="container py-5">
    <h1>
      Последние обновления на сайте
    </h1>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
        <br>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        {% endif %}
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    <hr>
    {% include 'posts/includes/paginator.html' %}
  </div>
</main>
{% endblock  %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block page-title %} Пост {{ post_text|truncatechars:30 }} {% endblock page-title %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post_text.pub_date|date:"d E Y" }}
          </li>  
          <li class="list-group-item">
              Группа: {{ post_text.group.title }}
             <br>
              {% if post_text.group %}
              <a href="{% url 'posts:group_list' post_text.group.slug %}">
                  все записи группы
                </a>
              {% endif %}
          </li>
          <li class="list-group-item">
            Автор: {{ post_text.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ counter }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post_text.author %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        <p>
          {{ post_text|linebreaks }}
        </p>
        {% if request.user == post_text.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post_text.pk %}">редактировать запись</a>
        {% endif %}
      </article>
    </div>
  </div>
</main>
{% endblock %}
             

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block page-title %} Профайл пользователя {{ author.get_full_name  }} {% endblock page-title %}
{% block content %}
    <main>
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name  }} </h1>
        <h3>Всего постов: {{ author.posts.count  }} </h3>   
        <article>
            {% for post in page_obj %}
            <article>
              <ul>
                <li>
                  Автор: {{ post.author.get_full_name }}
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul>
              <p>{{ post.text }}</p>
              <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
              <br>
              {% if post.group %}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
              {% endif %}
              {% if not forloop.last %}<hr>{% endif %}
            </article>
            {% endfor %}
            <hr>
            {% include 'posts/includes/paginator.html' %}
          </div>
      </div>
    </main>
  </body>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block page-title %}Вы вышли из системы{% endblock page-title %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Выход
          </div>
          <div class="card-body">
            <p>
              Вы вышли из своей учётной записи. Ждём вас снова!
            </p>
          </div> 
        </div> 
      </div>
    </div>
  </div>
</main>
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block page-title %}Войти{% endblock page-title %}
{% block content %}
{% load user_filters %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Войти на сайт
          </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3"
                {% if field.field.required %} 
                  aria-required="true"
                {% else %}
                  aria-required="false"
                {% endif %}
              >
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                <div>
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'password_reset' %}" class="btn btn-link">
                Забыли пароль?
              </a>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</main>

{% endblock %} 

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block page-title %}Пароль изменён{% endblock page-title %}
{% block header %}{% endblock %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Пароль изменён
          </div>
          <div class="card-body">
            <p>Пароль изменён успешно</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block page-title %}Изменение пароля{% endblock page-title %}
{% block content %}
{% load user_filters %}

<main>
  <div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                  Изменить пароль
                </div>
                <div class="card-body">
                  <form method="post" action=" ">
                    {% csrf_token %}
                    {% for field in form %}
                      <div class="form-group row my-3 p-3">
                        <label for="{{ field.id_for_label }}">
                          {{ field.label }}
                            {% if field.field.required %}                  
                              <span class="required text-danger" >*</span>
                            {% endif %}  
                        </label>
                        {{ field|addclass:"form-control" }}
                          {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                              {{ field.help_text|safe }}
                            </small>
                          {% endif %}
                        <br>
                      </div>
                      {% endfor %}
                      <br>
                      <div class="col-md-6 offset-md-4">              
                              <button type="submit" class="btn btn-primary">
                                  Изменить пароль
                              </button>
                      </div>
                  </form>

              </div> <!-- card body -->
          </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
</div>

{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block page-title %}Сброс пароля выполнен{% endblock page-title %}
{% block header %}{% endblock %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Сброс пароля выполнен
          </div>
          <div class="card-body">
            <p>Пароль изменён, всё получилось.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block page-title %}Новый пароль{% endblock page-title %}
{% block content %}
{% load user_filters %}
{% if validlink %}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
                Введите новый пароль
            </div>
            <div class="card-body">
              <form method="post" action=" ">
                {% csrf_token %}
                {% for field in form %}
                  <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
                        {{ field.label }}
                    </label>
                  </div>
                  <div class="col-md-6">
                    {{ field|addclass:"form-control" }}
                  </div>
                {% endfor %}
                <div class="col-md-6 offset-md-4">              
                  <button type="submit" class="btn btn-primary">
                    Назначить новый пароль
                  </button>
                </div>
              </form>
            </div> <!-- card body -->
          </div> <!-- card -->
        </div> <!-- col -->
       </div> <!-- row -->
    </div>
</main>

{% else %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Ошибка</div>
            <div class="card-body">
                <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endif %}

{% endblock %}